### ISSUE TITLE
source() does not return to the interpreter console...

### ISSUE THREAD

**Issue by stefanofornari** [stefanofornari/BshConsole#9]
when a script is ran with source() the interpreter stuck not returning to the console.

**Comment by nickl-** [comment]
ouch

**Comment by stefanofornari** [comment]
fixed with https://github.com/stefanofornari/BshConsole/commit/0d2b1e9da18126ea1aa2df392e498fedd7acb66f. closing.

**Comment by nickl-** [comment]
So what was the problem? I still don't see what magically happens at stefanofornari/BshConsole@0d2b1e9 where do you recover from the EOF? Do you even close the input anywhere? Can you recover from:

```
while (true) a++;
```

**Comment by stefanofornari** [comment]
I could not reproduce the problem, but I believe it was in the way I was
previously closing the stream.

Ste
